Controllers/ReportsIndividualsPoolsAuditController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using USF_Health_MVC_EF.Models;

namespace USF_Health_MVC_EF.Controllers
{
    public class ReportsIndividualsPoolsAuditController : Controller
    {
       
        private readonly USF_Health_MVC_EFContext _context;
        public ReportsIndividualsPoolsAuditController(USF_Health_MVC_EFContext context)
        {
            _context = context;
        }



        [Authorize("usfhealth_laboratory")]
        public IActionResult Index(int? type, DateTime? dateStart, DateTime? dateEnd, String ? poolResult, int ? poolID)
        {

            SqlDataAdapter dataAdapterPools = new SqlDataAdapter("usp_pools_select", Globals.connection);
            dataAdapterPools.SelectCommand.CommandType = System.Data.CommandType.StoredProcedure;

            System.Data.DataTable dataTablePools = new System.Data.DataTable();

            SqlParameter sqlParameterPools01 = new SqlParameter("type", 3);      //5
            sqlParameterPools01.IsNullable = false;
            dataAdapterPools.SelectCommand.Parameters.Add(sqlParameterPools01);

            dataAdapterPools.Fill(dataTablePools);
            List<SpPools> listPools = new List<SpPools>();

            for (int i = 0; i < dataTablePools.Rows.Count; i++)
            {
                SpPools item = new SpPools();
                DataRow dr = dataTablePools.Rows[i];

                item.poo_id = Int32.Parse(dr["poo_id"].ToString());
                listPools.Add(item);
            }
            ViewData["pools"] = listPools;


            if (type == 1)
            {
                SqlDataAdapter dataAdapter = new SqlDataAdapter("usp_audit_individuals_select", Globals.connection);
                dataAdapter.SelectCommand.CommandType = System.Data.CommandType.StoredProcedure;
                
                System.Data.DataTable dataTable = new System.Data.DataTable();

                SqlParameter sqlParameter01 = new SqlParameter("type", 2);      //5
                sqlParameter01.IsNullable = false;
                dataAdapter.SelectCommand.Parameters.Add(sqlParameter01);

                SqlParameter sqlParameter02 = new SqlParameter("date_start", dateStart);
                sqlParameter02.IsNullable = true;
                dataAdapter.SelectCommand.Parameters.Add(sqlParameter02);

                SqlParameter sqlParameter03 = new SqlParameter("date_end", dateEnd);
                sqlParameter03.IsNullable = true;
                dataAdapter.SelectCommand.Parameters.Add(sqlParameter03);

                SqlParameter sqlParameter04 = new SqlParameter("pr_result", poolResult);
                sqlParameter03.IsNullable = true;
                dataAdapter.SelectCommand.Parameters.Add(sqlParameter04);

                SqlParameter sqlParameter05 = new SqlParameter("poo_id", poolID);
                sqlParameter03.IsNullable = true;
                dataAdapter.SelectCommand.Parameters.Add(sqlParameter05);

                dataAdapter.Fill(dataTable);
                List<SpAudit> list = new List<SpAudit>();

                for (int i = 0; i < dataTable.Rows.Count; i++)
                {
                    SpAudit item = new SpAudit();
                    DataRow dr = dataTable.Rows[i];

                    item.aud_id = Int32.Parse(dr["aud_id"].ToString());
                    item.aud_operation_id = Int32.Parse(dr["aud_operation_id"].ToString());
                    item.aud_operation = dr["aud_operation"].ToString();
                    item.aud_date = dr["aud_date"] is DBNull ? (DateTime?)null : (DateTime?)dr["aud_date"];
                    item.aud_time = dr["aud_time"] is DBNull ? (TimeSpan?)null : (TimeSpan?)dr["aud_time"];
                    item.aud_table = dr["aud_table"].ToString();
                    item.aud_poo_id =  dr["aud_poo_id"] is DBNull ? 0 : Int32.Parse(dr["aud_poo_id"].ToString()); //Int32.Parse(dr["aud_poo_id"].ToString());
                    item.aud_identifier_id = dr["aud_identifier_id"].ToString();
                    item.aud_identifier_field = dr["aud_identifier_field"].ToString();
                    item.aud_field = dr["aud_field"].ToString();
                    item.aud_identifier_field = dr["aud_identifier_field"].ToString();
                    item.aud_before = dr["aud_before"].ToString();
                    item.aud_after = dr["aud_after"].ToString();
                    item.usr_id_audit = Int32.Parse(dr["usr_id_audit"].ToString());
                    item.usr_username = dr["usr_username"].ToString();
                    item.ssn_id = Int32.Parse(dr["ssn_id"].ToString());
                    list.Add(item);
                }

                return View(list);
            }
            else
            {
                SqlDataAdapter dataAdapter = new SqlDataAdapter("usp_audit_individuals_select", Globals.connection);
                dataAdapter.SelectCommand.CommandType = System.Data.CommandType.StoredProcedure;
                System.Data.DataTable dataTable = new System.Data.DataTable();
                dataAdapter.Fill(dataTable);
                List<SpAudit> list = new List<SpAudit>();

                for (int i = 0; i < dataTable.Rows.Count; i++)
                {
                    SpAudit item = new SpAudit();
                    DataRow dr = dataTable.Rows[i];

                    item.aud_id = Int32.Parse(dr["aud_id"].ToString());
                    item.aud_operation_id = Int32.Parse(dr["aud_operation_id"].ToString());
                    item.aud_operation = dr["aud_operation"].ToString();
                    item.aud_date = dr["aud_date"] is DBNull ? (DateTime?)null : (DateTime?)dr["aud_date"];
                    item.aud_time = dr["aud_time"] is DBNull ? (TimeSpan?)null : (TimeSpan?)dr["aud_time"];
                    item.aud_table = dr["aud_table"].ToString();
                    item.aud_poo_id = Int32.Parse(dr["aud_poo_id"].ToString());
                    item.aud_identifier_id = dr["aud_identifier_id"].ToString();
                    item.aud_identifier_field = dr["aud_identifier_field"].ToString();
                    item.aud_field = dr["aud_field"].ToString();
                    item.aud_identifier_field = dr["aud_identifier_field"].ToString();
                    item.aud_before = dr["aud_before"].ToString();
                    item.aud_after = dr["aud_after"].ToString();
                    item.usr_id_audit = Int32.Parse(dr["usr_id_audit"].ToString());
                    item.usr_username = dr["usr_username"].ToString();
                    item.ssn_id = Int32.Parse(dr["ssn_id"].ToString());
                    list.Add(item);
                }

                return View(list);
            }
        }

    }
}

Views/ReportsIndividualsPoolsAudit/Index.cshtml
@model IEnumerable<USF_Health_MVC_EF.Models.SpAudit>

@{
    ViewData["Title"] = "Reports - Individuals Pools Audit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<SpPools> spPools = ViewData["pools"] as List<SpPools>;
}
<script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.dataTables.min.css" runat=server>

<div class="div_breadcrumb">
    Reports&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;Individuals Pools Audit
</div>

<script type="text/javascript">

    $(document).ready(function () {
        $('#example').DataTable({
            columnDefs: [{
                targets: [0],
                orderData: [0, 1]
            }, {
                targets: [1],
                orderData: [1, 0]
            }, {
                targets: [4],
                orderData: [4, 0]
                }],
            dom: 'Bfrtip',
            buttons: [
                {
                    extend: 'pdfHtml5',
                    orientation: 'landscape',
                    pageSize: 'LEGAL'
                },

                'copy', 'csv', 'excel', 'print'
            ]
        });
    });

</script>



<div class="div_form" style="width:80%">

    <form id="frmForm">
        <div>
            <div style="float: left;  width:30%;">
                <div class="div_text">
                    Audit Date Start
                </div>
                <div class="div_input">
                    <input type="date" id="txtDateStart" required />
                </div>

                <div class="div_text">
                    Audit Date End
                </div>
                <div class="div_input">
                    <input type="date" id="txtDateEnd" required />
                </div>

                <div class="div_button">
                    <input type="submit" id="btnSubmit" value="Search" onclick="handle(event,document.getElementById('txtDateStart').value, document.getElementById('txtDateEnd').value, document.getElementById('ddlPoolResult').options[document.getElementById('ddlPoolResult').selectedIndex].value, document.getElementById('ddlPoolID').options[document.getElementById('ddlPoolID').selectedIndex].value, document.getElementById('ddlPoolResult').selectedIndex, document.getElementById('ddlPoolID').selectedIndex, document.getElementById('ddlPoolResult').options[document.getElementById('ddlPoolResult').selectedIndex].text, document.getElementById('ddlPoolID').options[document.getElementById('ddlPoolID').selectedIndex].text);" />
                </div>

                <div class="div_label" style="width:800px;">
                    <label id="lblStatus"></label>
                </div>
                <div class="div_label" style="width:800px;">
                    <label id="lblPoolResultStatus"></label>
                </div>
                <div class="div_label" style="width:800px;">
                    <label id="lblPoolIDStatus"></label>
                </div>
                <div class="div_label" style="width:800px;">
                    <label id="lblSeparator"></label>
                </div>
            </div>
            <div style="float: left;  width:10%;">
                <div class="div_text">
                    AND
                </div>
            </div>
            <div style="float: left; width:30%;">
                <div class="div_text">
                    Pool Result
                </div>
                <div class="div_dropdownlist">
                    <select id="ddlPoolResult">
                        <option value="A">All Results</option>
                        <option value="P">Positive (P)</option>
                        <option value="N">Negative (N)</option>
                        <option value="U">Pools w/ No Result</option>
                    </select>
                </div>
            </div>
            <div style="float: left;  width:10%;">
                <div class="div_text">
                    AND
                </div>
            </div>
            <div style="float: right; width:20%;">
                <div class="div_text">
                    Pool ID
                </div>
                <div class="div_dropdownlist">
                    <select id="ddlPoolID">
                        <option value="0" selected>All Pools</option>
                        @foreach (var item in spPools)
                        {
                            <option value="@item.poo_id">@item.poo_id</option>

                        }
                    </select>
                </div>
            </div>

        </div>
</form>
</div>


@using (Html.BeginForm("Index", "SpPools", FormMethod.Post))
{
    <div class="div_datatables">

        <table id="example" class="display" style="width:100%">
            <thead>
                <tr>
                    <td>
                        Audit ID
                    </td>
                    @*<td>
                        Audit Operation ID
                    </td>*@
                    <td>
                        Audit Operation
                    </td>
                    <td>
                        Audit Date
                    </td>
                    <td>
                        Audit Time
                    </td>
                    <td>
                        Audit Table
                    </td>
                    <td>
                        Audit Pool ID
                    </td>
                    <td>
                        Audit Identifier ID
                    </td>
                    <td>
                        Audit Identifier Field
                    </td>
                    <td>
                        Audit Field
                    </td>
                    <td>
                        Audit Before
                    </td>
                    <td>
                        Audit After
                    </td>
                    <td>
                        Audit User
                    </td>
                    <td>
                        Session ID
                    </td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.aud_id, new { htmlAttributes = new { @id = "aud_id" + item.aud_id } })
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.aud_operation_id)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.aud_operation)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.aud_date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.aud_time)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.aud_table)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.aud_poo_id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.aud_identifier_id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.aud_identifier_field)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.aud_field)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.aud_before)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.aud_after)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.usr_username)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ssn_id)
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>}




<script type="text/javascript">

    function handle(e, dateStart, dateEnd, poolResult, PoolID, poolResultSelected, poolIDSelected, poolResultStatus, poolIDStatus) {


        if (e.keyCode === 13 || e.target.id == 'btnSubmit') {
            if (document.getElementById('frmForm').checkValidity()) {
                e.preventDefault();
                ReportsIndividualsPoolsAudit(dateStart, dateEnd, poolResult, PoolID, poolResultSelected, poolIDSelected, poolResultStatus, poolIDStatus);
            }
        }
    }


    function ReportsIndividualsPoolsAudit(dateStart, dateEnd, poolResult, PoolID, poolResultSelected, poolIDSelected, poolResultStatus, poolIDStatus) {
        window.location.href = '@Url.Action("Index", "ReportsIndividualsPoolsAudit")?type=1&datestart=' + dateStart + '&dateend=' + dateEnd + '&poolResult=' + poolResult + '&poolID=' + PoolID + '&poolResultSelected=' + poolResultSelected + '&poolIDSelected=' + poolIDSelected + '&status=Audit Dates: from ' + dateStart + ' to ' + dateEnd + '&poolResultStatus=' + poolResultStatus + '&poolIDStatus=' + poolIDStatus;
    }
</script>

<script type="text/javascript">

    const params = new URLSearchParams(window.location.search);
    const type = params.get('type');
    const status = params.get('status');
    const poolResultStatus = params.get('poolResultStatus');
    const poolIDStatus = params.get('poolIDStatus');
    const dateStart = params.get('datestart');
    const dateEnd = params.get('dateend');
    const poolResultSelected = params.get('poolResultSelected');
    const poolIDSelected = params.get('poolIDSelected');

    if (type == null) {
        document.getElementById('lblStatus').hidden = true;
    } else if (type == 0) {
        document.getElementById('lblStatus').hidden = false;
        document.getElementById('lblStatus').style.color = "green";
        document.getElementById('lblStatus').textContent = status
    } else if (type == 1) {
        document.getElementById('txtDateStart').value = dateStart;
        document.getElementById('txtDateEnd').value = dateEnd;
        document.getElementById('ddlPoolResult').selectedIndex = poolResultSelected;
        document.getElementById('ddlPoolID').selectedIndex = poolIDSelected;

        document.getElementById('lblStatus').hidden = false;
        document.getElementById('lblStatus').style.color = "green";
        document.getElementById('lblStatus').textContent = status

        document.getElementById('lblPoolResultStatus').hidden = false;
        document.getElementById('lblPoolResultStatus').style.color = "green";
        document.getElementById('lblPoolResultStatus').textContent = 'Pool Result: '+ poolResultStatus

        document.getElementById('lblPoolIDStatus').hidden = false;
        document.getElementById('lblPoolIDStatus').style.color = "green";
        document.getElementById('lblPoolIDStatus').textContent = 'Pool ID: ' + poolIDStatus


    }

</script>

<script type="text/javascript">

    $('form').submit(function () {
        $(this).find('input[type=submit]').prop('disabled', true);
        return true;
    });

    $("#btnSubmit").focus();

</script>