Controllers/PersonsPoolsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Logging;
using USF_Health_MVC_EF.Models;

namespace USF_Health_MVC_EF.Controllers
{
    public class PersonsPoolsController : Controller
    {

        private readonly USF_Health_MVC_EFContext _context;


        public PersonsPoolsController(USF_Health_MVC_EFContext context)
        {
            _context = context;
        }

        [Authorize("usfhealth_laboratory")]
        public ActionResult Index(string? search)
        {

            //SqlDataAdapter dataAdapter = new SqlDataAdapter("usp_pools_select", Globals.connection);
            //dataAdapter.SelectCommand.CommandType = System.Data.CommandType.StoredProcedure;
            //System.Data.DataTable dataTable = new System.Data.DataTable();

            //dataAdapter.Fill(dataTable);

            //List<SpPools> list = new List<SpPools>();

            //for (int i = 0; i < dataTable.Rows.Count; i++)
            //{

            //    SpPools item = new SpPools();
            //    DataRow dr = dataTable.Rows[i];

            //    item.poo_id = Int32.Parse(dr["poo_id"].ToString());
            //    item.poo_date_created_text = dr["poo_date_created_text"].ToString();
            //    item.poo_details = dr["poo_details"].ToString();
            //    item.pr_result = dr["pr_result"].ToString();
            //    item.pr_ct_value = dr["pr_ct_value"].ToString();
            //    item.poo_count = Int32.Parse(dr["poo_count"].ToString());

            //    list.Add(item);
            //}

            //return View(list);

            //SqlDataAdapter dataAdapter = new SqlDataAdapter("usp_pools_select", Globals.connection);
            //dataAdapter.SelectCommand.CommandType = System.Data.CommandType.StoredProcedure;
            //System.Data.DataTable dataTable = new System.Data.DataTable();

            //dataAdapter.Fill(dataTable);

            SqlCommand sqlCommand = new SqlCommand();
            SqlConnection sqlConnection = new SqlConnection(Globals.connection.ToString());
            sqlCommand.CommandType = System.Data.CommandType.StoredProcedure;
            sqlCommand.Connection = sqlConnection;
            sqlCommand.CommandText = "usp_pools_select";

            SqlParameter sqlParameter01 = new SqlParameter("type", 4);
            sqlParameter01.IsNullable = true;
            sqlCommand.Parameters.Add(sqlParameter01);


            SqlParameter sqlParameter02 = new SqlParameter("search", Globals.Iif(search is null, "", search));
            sqlParameter02.IsNullable = true;
            sqlCommand.Parameters.Add(sqlParameter02);

            SqlDataAdapter dataAdapter = new SqlDataAdapter(sqlCommand); //I think the problem is here, how am I fixing it though? --Fixed but why can't it be put into a class?
            System.Data.DataTable dataTable = new System.Data.DataTable();

            dataAdapter.Fill(dataTable);

            List<SpPools> list = new List<SpPools>();

            for (int i = 0; i < dataTable.Rows.Count; i++)
            {

                SpPools item = new SpPools();
                DataRow dr = dataTable.Rows[i];

                item.poo_id = Int32.Parse(dr["poo_id"].ToString());
                item.poo_date_created_text = dr["poo_date_created_text"].ToString();
                item.poo_details = dr["poo_details"].ToString();
                item.pr_result = dr["pr_result"].ToString();
                item.pr_ct_value = dr["pr_ct_value"].ToString();
                item.poo_count = Int32.Parse(dr["poo_count"].ToString());

                list.Add(item);
            }

            return View(list);

        }

        [Authorize("usfhealth_laboratory")]
        public ActionResult Assign(int? id)
        {
            SqlDataAdapter dataAdapter = new SqlDataAdapter("usp_individuals_samples_select", Globals.connection);
            dataAdapter.SelectCommand.CommandType = System.Data.CommandType.StoredProcedure;
            System.Data.DataTable dataTable = new System.Data.DataTable();

            SqlParameter sqlParameter01 = new SqlParameter("type", 5);  //4
            SqlParameter sqlParameter02 = new SqlParameter("poo_id", id);

            dataAdapter.SelectCommand.Parameters.Add(sqlParameter01);
            dataAdapter.SelectCommand.Parameters.Add(sqlParameter02);

            dataAdapter.Fill(dataTable);

            List<SpIndividualsSamples> list = new List<SpIndividualsSamples>();

            for (int i = 0; i < dataTable.Rows.Count; i++)
            {
                SpIndividualsSamples item = new SpIndividualsSamples();
                DataRow dr = dataTable.Rows[i];

                item.is_id = Int32.Parse(dr["is_id"].ToString());
                item.is_barcode = dr["is_barcode"].ToString();
                item.ind_id = Int32.Parse(dr["ind_id"].ToString());
                item.ind_first_name = dr["ind_first_name"].ToString();
                item.ind_last_name = dr["ind_last_name"].ToString();
                item.ind_gender = dr["ind_gender"].ToString();
                item.ref_id = Int32.Parse(dr["ref_id"].ToString());
                item.ref_name = dr["ref_name"].ToString();
                item.std_id = Int32.Parse(dr["std_id"].ToString());
                item.std_name = dr["std_name"].ToString();
                item.first_name_last_name = dr["first_name_last_name"].ToString();
                item.is_date_created = dr["is_date_created"] is DBNull ? (DateTime?)null : (DateTime?)dr["is_date_created"];
                item.is_time_created = dr["is_time_created"] is DBNull ? (TimeSpan?)null : (TimeSpan?)dr["is_time_created"];
                item.is_date_created_text = dr["is_date_created_text"].ToString();
                item.is_date_collected = dr["is_date_collected"] is DBNull ? (DateTime?)null : (DateTime?)dr["is_date_collected"];
                item.is_time_collected = dr["is_time_collected"] is DBNull ? (TimeSpan?)null : (TimeSpan?)dr["is_time_collected"];
                item.is_date_collected_text = dr["is_date_collected_text"].ToString();
                item.is_details = dr["is_details"].ToString();
                item.poo_id = Int32.Parse(dr["poo_id"].ToString());
                item.poo_details = dr["poo_details"].ToString();
                item.is_date_registered = dr["is_date_registered"] is DBNull ? (DateTime?)null : (DateTime?)dr["is_date_registered"];
                item.is_time_registered = dr["is_time_registered"] is DBNull ? (TimeSpan?)null : (TimeSpan?)dr["is_time_registered"];
                item.is_date_registered_text = dr["is_date_registered_text"].ToString();
                item.is_date_registered_pool = dr["is_date_registered_pool"] is DBNull ? (DateTime?)null : (DateTime?)dr["is_date_registered_pool"];
                item.is_time_registered_pool = dr["is_time_registered_pool"] is DBNull ? (TimeSpan?)null : (TimeSpan?)dr["is_time_registered_pool"];
                item.is_date_registered_pool_text = dr["is_date_registered_pool_text"].ToString();
                item.is_details = dr["is_details"].ToString();
                item.position = Int32.Parse(dr["position"].ToString());

                list.Add(item);
            }

            ViewBag.poo_id = id;

            return View(list);
        }




        [Authorize("usfhealth_laboratory")]
        public ActionResult Details(int? id)
        {
            SqlDataAdapter dataAdapter = new SqlDataAdapter("usp_individuals_samples_select", Globals.connection);
            dataAdapter.SelectCommand.CommandType = System.Data.CommandType.StoredProcedure;
            System.Data.DataTable dataTable = new System.Data.DataTable();

            SqlParameter sqlParameter01 = new SqlParameter("type", 5);  //4
            SqlParameter sqlParameter02 = new SqlParameter("poo_id", id);

            dataAdapter.SelectCommand.Parameters.Add(sqlParameter01);
            dataAdapter.SelectCommand.Parameters.Add(sqlParameter02);

            dataAdapter.Fill(dataTable);

            List<SpIndividualsSamples> list = new List<SpIndividualsSamples>();

            for (int i = 0; i < dataTable.Rows.Count; i++)
            {
                SpIndividualsSamples item = new SpIndividualsSamples();
                DataRow dr = dataTable.Rows[i];

                item.is_id = Int32.Parse(dr["is_id"].ToString());
                item.is_barcode = dr["is_barcode"].ToString();
                item.ind_id = Int32.Parse(dr["ind_id"].ToString());
                item.ind_first_name = dr["ind_first_name"].ToString();
                item.ind_last_name = dr["ind_last_name"].ToString();
                item.ind_gender = dr["ind_gender"].ToString();
                item.ref_id = Int32.Parse(dr["ref_id"].ToString());
                item.ref_name = dr["ref_name"].ToString();
                item.std_id = Int32.Parse(dr["std_id"].ToString());
                item.std_name = dr["std_name"].ToString();
                item.first_name_last_name = dr["first_name_last_name"].ToString();
                item.is_date_created = dr["is_date_created"] is DBNull ? (DateTime?)null : (DateTime?)dr["is_date_created"];
                item.is_time_created = dr["is_time_created"] is DBNull ? (TimeSpan?)null : (TimeSpan?)dr["is_time_created"];
                item.is_date_created_text = dr["is_date_created_text"].ToString();
                item.is_date_collected = dr["is_date_collected"] is DBNull ? (DateTime?)null : (DateTime?)dr["is_date_collected"];
                item.is_time_collected = dr["is_time_collected"] is DBNull ? (TimeSpan?)null : (TimeSpan?)dr["is_time_collected"];
                item.is_date_collected_text = dr["is_date_collected_text"].ToString();
                item.is_details = dr["is_details"].ToString();

Views/PersonsPools/Assign.cshtml
@model IEnumerable<USF_Health_MVC_EF.Models.SpIndividualsSamples>

@{
    ViewData["Title"] = "Assign";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="div_breadcrumb">
    Persons&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;Pools&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;Assign
</div>



<script type="text/javascript">

    $(document).ready(function () {
        $('#example').DataTable({
            columnDefs: [{
                targets: [0],
                orderData: [0, 1]
            }, {
                targets: [1],
                orderData: [1, 0]
            }, {
                targets: [4],
                orderData: [4, 0]
            }]
        });
    });

</script>



<div class="div_form">

    <form id="frmForm">
        <input type="hidden" id="poo_id" value="@ViewBag.poo_id" />


        <div class="div_bigtitle">
            Details for Pool ID @ViewBag.poo_id
        </div>
        <div class="div_input">
            <input type="text" id="txtBarcode" placeholder="Enter barcode" required onkeydown="handle(event,document.getElementById('txtBarcode').value,document.getElementById('poo_id').value)" autofocus />
        </div>

        <div class="div_button">
            <input type="submit" id="btnSubmit" value="Assign" onclick="handle(event,document.getElementById('txtBarcode').value, document.getElementById('poo_id').value);" onsubmit="this.disabled = true;this.value='Submitting...';this.form.submit();" />
        </div>

        <div class="div_label" style="width:500px;">
            <label id="lblStatus"></label>
        </div>

        <div class="div_label" style="width:800px;">
            <label id="lblSeparator"></label>
        </div>

    </form>
</div>


@using (Html.BeginForm("Index", "PersonSamples", FormMethod.Post))
{
    <div class="div_datatables">

        <table id="example" class="display" style="width:100%">
            <thead>
                <tr>
                    <td>
                        Sample ID
                    </td>
                    <td>
                        Barcode
                    </td>
                    <td>
                        Pool ID
                    </td>
                    <td>
                        Pool Details
                    </td>
                    <td>
                        Date created
                    </td>
                    <td>
                        Date collected
                    </td>
                    <td>
                        Date registered
                    </td>
                    <td>
                        Sample Details
                    </td>
                    <td>
                        Reference ID
                    </td>
                    <td>
                        Study ID
                    </td>
                    <td>
                        Gender
                    </td>

                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_id, new { htmlAttributes = new { @id = "is_id_" + item.is_id } })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_barcode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.poo_id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.poo_details)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_date_created_text)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_date_collected_text)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_date_registered_text)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_details)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ref_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.std_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ind_gender)
                    </td>
                    <td>
                        <a asp-action="Unassign" asp-route-id="@item.is_id" asp-route-poo_id="@ViewBag.poo_id" asp-route-search="@Context.Request.Query["search"].ToString()">Unassign</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
}


<div class="div_mainlink">
    <a asp-action="Index" asp-route-search="@Context.Request.Query["search"].ToString()">Back to List</a>
</div>

<script type="text/javascript">

    function handle(e, id, value) {


        if (e.keyCode === 13 || e.target.id == 'btnSubmit') {
            if (document.getElementById('frmForm').checkValidity()) {
                e.preventDefault();
                UpdatePoolID(id, value, 1);
            }
        }
    }


    function UpdatePoolID(id, value, operation) {

        const params = new URLSearchParams(window.location.search);
        const search = params.get('search');

        if (document.getElementById('frmForm').checkValidity()) {
              $.ajax({
                url: '@Url.Action("UpdatePoolID")',
                type: 'GET',
                dataType: 'text',
                cache: false,
                    data: { 'id': id, 'value': value, 'operation': 1},
                      success: function (results) {
                          window.location.href = '@Url.Action("Assign", "PersonsPools")?type=1&status=' + results + '&search=' + search + '';
                },
                error: function () {
                    alert('Error occured');
                }
            });

        }

    }


</script>



<script type="text/javascript">

    $('form').submit(function () {
        $(this).find('input[type=submit]').prop('disabled', true);
        return true;
    });

    $("#btnSubmit").focus();

</script>



<script type="text/javascript">

    const params = new URLSearchParams(window.location.search);
    const type = params.get('type');
    const status = params.get('status');

    if (type == null) {
        document.getElementById('lblStatus').hidden = true;
    } else if (type == 0) {
        document.getElementById('lblStatus').hidden = false;
        document.getElementById('lblStatus').style.color = "green";
        document.getElementById('lblStatus').textContent = status
    } else if (type == 1) {
        document.getElementById('lblStatus').hidden = false;
        document.getElementById('lblStatus').style.color = "green";
        document.getElementById('lblStatus').textContent = status

    }

</script>

<script type="text/javascript">
    $("#txtBarcode").focus();
</script>

Views/PersonsPools/Create.cshtml
@model USF_Health_MVC_EF.Models.Pool

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="div_breadcrumb">
    Persons&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;Pools&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;Create New
</div>
    <div class="div_form">
        <form asp-action="Create">

            <div class="div_textArea">
                <textarea asp-for="poo_details" class="textArea" rows="5" cols="36" placeholder="Enter pool details"></textarea>
            </div>

            <div class="div_button">
                <input type="submit" id="btnSubmit" value="Create" onsubmit="this.disabled = true;this.value='Submitting...';this.form.submit();" />
            </div>
        </form>
    </div>
    
    <div class="div_mainlink">
        <a asp-action="Index" asp-route-search="@Context.Request.Query["search"].ToString()">Back to List</a>
    </div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script type="text/javascript">

    $('form').submit(function () {
        $(this).find('input[type=submit]').prop('disabled', true);
        return true;
    });

</script>

Views/PersonsPools/Delete.cshtml
@model USF_Health_MVC_EF.Models.SpPools

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<div class="div_breadcrumb">
    Persons&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;Pools&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;Delete
</div>
<div class="div_form">
    <div class="div_text">
        Are you sure you want to delete this pool?
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Pool ID
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => Model.poo_id)
        </div>
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Date created
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => Model.poo_date_created_text)
        </div>
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Pool Details
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => Model.poo_details)
        </div>
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;color:red;background-color:yellow;">
            Barcodes count
        </div>
        <div class="div_text" style="color:red;background-color:yellow;font-weight:bold;">
            @Html.DisplayFor(model => Model.poo_count) (all samples will be unassigned)
        </div>
    </div>


    <form id="frmForm">
        <input type="hidden" id="poo_id" value="@Model.poo_id" />

        <div class="div_button">
            <input type="submit" value="Delete" id="btnSubmit" style="background-color: #bd2130;" onclick="handle(event,0, document.getElementById('poo_id').value);" />
        </div>
    </form>
</div>

<div class="div_mainlink">
    <a asp-action="Index" asp-route-search="@Context.Request.Query["search"].ToString()">Back to List</a>
</div>

<script type="text/javascript">

    $('form').submit(function () {
        $(this).find('input[type=submit]').prop('disabled', true);
        return true;
    });

    $("#btnSubmit").focus();

</script>



<script type="text/javascript">

    function handle(e, id, value) {

        if (e.keyCode === 13 || e.target.id == 'btnSubmit') {
            if (document.getElementById('frmForm').checkValidity()) {
                e.preventDefault();
                UpdatePoolID(id, value, 3);
            }
        }
    }

    function UpdatePoolID(id, value, operation) {

        const params = new URLSearchParams(window.location.search);
        const search = params.get('search');

        if (document.getElementById('frmForm').checkValidity()) {
              $.ajax({
                url: '@Url.Action("UpdatePoolID")',
                type: 'GET',
                dataType: 'text',
                cache: false,
                  data: { 'id': id, 'value': value, 'operation': operation},
                      success: function (results) {
                          window.location.href = '@Url.Action("Index", "PersonsPools")?search=' + search +'';
                },
                error: function () {
                    alert('Error occured');
                }
            });

        }

    }


</script>

Views/PersonsPools/Details.cshtml
@model IEnumerable<USF_Health_MVC_EF.Models.SpIndividualsSamples>

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div class="div_breadcrumb">
        Persons&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;Pools&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;Details
    </div>



<script type="text/javascript">

    $(document).ready(function () {
        $('#example').DataTable({
            columnDefs: [{
                targets: [0],
                orderData: [0, 1]
            }, {
                targets: [1],
                orderData: [1, 0]
            }, {
                targets: [4],
                orderData: [4, 0]
            }]
        });
    });

</script>

<div class="div_form">

    <form id="frmForm">
        <input type="hidden" id="poo_id" value="@ViewBag.poo_id" />


        <div class="div_bigtitle">
            Details for Pool ID @ViewBag.poo_id
        </div>

    </form>
</div>


@using (Html.BeginForm("Index", "PersonSamples", FormMethod.Post))
{
    <div class="div_datatables">

        <table id="example" class="display" style="width:100%">
            <thead>
                <tr>
                    <td>
                        Sample ID
                    </td>
                    <td>
                        Barcode
                    </td>
                    <td>
                        Pool ID
                    </td>
                    <td>
                        Pool Details
                    </td>
                    <td>
                        Date of creation
                    </td>
                    <td>
                        Date of collection
                    </td>
                    <td>
                        Date registered
                    </td>
                    <td>
                        Sample Details
                    </td>
                    <td>
                        Reference ID
                    </td>
                    <td>
                        Study ID
                    </td>
                    <td>
                        Gender
                    </td>

                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_id, new { htmlAttributes = new { @id = "is_id_" + item.is_id } })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_barcode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.poo_id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.poo_details)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_date_created_text)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_date_collected_text)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_date_registered_text)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.is_details)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ref_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.std_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ind_gender)
                    </td>
                    <td>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
}


<div class="div_mainlink">
    <a asp-action="Index" asp-route-search="@Context.Request.Query["search"].ToString()">Back to List</a>
</div>



<script type="text/javascript">

    $('form').submit(function () {
        $(this).find('input[type=submit]').prop('disabled', true);
        return true;
    });

    $("#btnSubmit").focus();

</script>

Views/PersonsPools/Unassign.cshtml
@model USF_Health_MVC_EF.Models.SpIndividualsSamples

@{
    ViewData["Title"] = "Unassign";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<div class="div_breadcrumb">
    Persons&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;Pools&nbsp;&nbsp;&nbsp;>&nbsp;&nbsp;&nbsp;Unassign
</div>
<div class="div_form">
    <div class="div_text">
        Are you sure you want to unassign this barcode from the pool?
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Sample Id
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => model.is_id)
        </div>
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Sample Barcode
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => model.is_barcode, new { htmlAttributes = new { @id = "txtBarcode" } })
        </div>
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Pool ID
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => model.poo_id)
        </div>
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Date created
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => model.is_date_created_text)
        </div>
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Date collected
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => model.is_date_collected_text)
        </div>
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Date registered
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => model.is_date_registered_text)
        </div>
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Date registered pool
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => model.is_date_registered_pool_text)
        </div>
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Reference ID
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => model.ref_name)
        </div>
    </div>


    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Study ID
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => model.std_name)
        </div>
    </div>


    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Gender
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => model.ind_gender)
        </div>
    </div>

    <div class="div_labeltext">
        <div class="div_label" style="float:left;">
            Sample Details
        </div>
        <div class="div_text">
            @Html.DisplayFor(model => model.is_details)
        </div>
    </div>

    <form id="frmForm">
        <input type="hidden" id="poo_id" value="@ViewBag.poo_id" />
        <input type="hidden" id="is_barcode" value="@ViewBag.is_barcode" />

        <div class="div_button">
            <input type="submit" value="Unassign" id="btnSubmit" style="background-color: #bd2130;" onclick="handle(event,document.getElementById('is_barcode').value, document.getElementById('poo_id').value);" />
        </div>
    </form>

</div>
<div class="div_mainlink">
    <a asp-action="Assign" asp-route-id="@ViewBag.poo_id" asp-route-search="@Context.Request.Query["search"].ToString()">Back to List</a>
</div>

<script type="text/javascript">

    $('form').submit(function () {
        $(this).find('input[type=submit]').prop('disabled', true);
        return true;
    });

    $("#btnSubmit").focus();

</script>



<script type="text/javascript">

    function handle(e, id, value) {

        if (e.keyCode === 13 || e.target.id == 'btnSubmit') {
            if (document.getElementById('frmForm').checkValidity()) {
                e.preventDefault();
                UpdatePoolID(id, value, 2);
            }
        }
    }


    function UpdatePoolID(id, value, operation) {

        const params = new URLSearchParams(window.location.search);
        const search = params.get('search');

        if (document.getElementById('frmForm').checkValidity()) {
              $.ajax({
                url: '@Url.Action("UpdatePoolID")',
                type: 'GET',
                dataType: 'text',
                cache: false,
                    data: { 'id': id, 'value': value, 'operation': 2},
                      success: function (results) {
                          window.location.href = '@Url.Action("Assign", "PersonsPools", new { id = ViewBag.poo_id })?type=0&status=' + results + '&search=' + search + '';
                },
                error: function () {
                    alert('Error occured');
                }
            });

        }

    }


</script>